AWSTemplateFormatVersion: '2010-09-09'
################################################################################
#
# DESCRIPTION
#
################################################################################
################################################################################
#
# RESOURCES
#
################################################################################
Resources:
  rECRRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: hello-server

  rECRRepoParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ECR Repository
      Name: ecr-repo-name
      Type: String
      Value: !Ref rECRRepo

  rTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: hello-server
          Image:  '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/hello-server'
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
              Protocol: tcp
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/hello-server
              awslogs-region: eu-west-1
              awslogs-stream-prefix: ecs
      Family: hello-server
      NetworkMode: bridge
      Memory: 256
      RequiresCompatibilities:
        - EC2

  rECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/hello-server

  rTargetGroup:  # Moved this into the Resources section
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: hello-server-tg
      TargetType: instance
      HealthCheckIntervalSeconds: 5
      HealthCheckPath: /ping
      HealthCheckTimeoutSeconds: 3
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      VpcId:  '{{resolve:ssm:vpc}}'
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '5'

Outputs:
  ECSTaskDefinition:
    Description: The created TaskDefinition.
    Value: !Ref rTaskDefinition
